# Generated by Django 3.2.6 on 2022-06-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoria_id', models.IntegerField(blank=True, null=True)),
                ('kategoria_nazwa', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UstawieniaStan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czy_sprawdzony', models.BooleanField(default=False)),
                ('czy_zlecono_synchronizacje', models.BooleanField(default=False)),
            ],
        ),
    ]
