# Generated by Django 3.2.6 on 2022-06-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ustawieniastan',
            name='ostatnia_data',
            field=models.DateTimeField(default='2021-01-05 06:00:00.000000-09:00'),
        ),
    ]
