# Generated by Django 3.2.6 on 2022-06-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ustawieniastan_ostatnia_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ustawieniastan',
            name='nazwa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
